### ISSUE TITLE
Update link to WMF specification in README

### ISSUE THREAD

**Issue by B3zaleel** [papnkukn/wmf#2]
The link to the WMF specification in the README appears to be dead. Could you consider updating it with a live link?

Some options I found:

+ [loc.gov](https://www.loc.gov/preservation/digital/formats/digformatspecs/WindowsMetafileFormat(wmf)Specification.pdf)
- [microsoft](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-WMF/%5bMS-WMF%5d.pdf) from [here](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-wmf/4813e7fd-52d0-4f42-965f-228c8b7488d2)

**Comment by ForNeVeR** [comment]
Closed in a fork repository by https://github.com/wieslawsoltes/wmf/pull/4.
